CREATE TABLE IF NOT EXISTS tb_grupo(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	descricao VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO tb_grupo (descricao) VALUES('ADMINISTRADORES');
INSERT INTO tb_grupo (descricao) VALUES('MÉDICOS');
INSERT INTO tb_grupo (descricao) VALUES('SECRETÁRIAS');