CREATE TABLE IF NOT EXISTS tb_paciente(
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	email VARCHAR(100) NOT NULL,
	PRIMARY KEY(id)
) ENGINE=InnoDB CHARSET=UTF8;